# the location of the hisat2 index (it will be generated if it does
# not exist)
metadir: "/meta"

# the location of the fasta and gtf files relative to the `metadir`.
# If not specified the first available fasta/gtf files in the
# `metadir` will be used

# fasta: ""
# gtf: ""

# single end, forward stranded
rnastrandness: "-rna-strandness FR" 

# mode: "auto"

# see http://www.usadellab.org/cms/?page=trimmomatic for details
trimmer:
  - "LEADING:3"
  - "TRAILING:3"
  - "SLIDINGWINDOW:4:15"
  - "MINLEN:10"
  - "ILLUMINACLIP:TruSeq3-SE:2:30:10"
